### ISSUE TITLE
1.0.7.2, immortal baby husk

### ISSUE THREAD

**Issue by kodamant** [lgow/endofherobrine#11]
baby husks, only when spawning naturally, and only in survival mode, are immune to all forms of attack, also changing gamemode to creative makes them suddenly mortal like theyre supposed to be

To Reproduce
step one: have fun in minecraft
step two: find possesed baby husk
step three: contain the anomaly

Expected behavior
well i expected to be able to kill it

Environment

Minecraft Version:1.20.1
Mod Version:

**Comment by ServiPixel** [comment]
I'm having the same problem - The only solution so that my world is not filled with baby husk is to deactivate the possession of mobs
