### ISSUE TITLE
The End Of Herobrine 1.19 2-1.0.7.1 Bug

### ISSUE THREAD

**Issue by Boogy-Mobster** [lgow/endofherobrine#19]
Almost every time Herobrine shows up and stands there he leaves behind a baby zombie with a fishing rod. Its always the same mob. The mob that he leaves behind does not move, attack, or do anything but stand there. This gets in the way of building since it still registers as a real mob. This is annoying but not game-breaking.

**Comment by lgow** [comment]
this has been fixed already, update the mod to the latest version and it should be fine
