### ISSUE TITLE
totems dont work

### ISSUE THREAD

**Issue by EnzoBorrelli** [lgow/endofherobrine#2]
so, i built the structure, he speaks to me, but never show up. Only the regular blindness herobrine appears

**Comment by toledkrw** [comment]
Same here.

**Comment by lgow** [comment]
Which version?

**Comment by toledkrw** [comment]
MC - 1.19.2

**Comment by VenusSapphire** [comment]
> so, i built the structure, he speaks to me, but never show up. Only the regular blindness herobrine appears

this is happening to me too but in version 1.0.8.2 for version 1.19.2
