### ISSUE TITLE
Crash 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [lgow/endofherobrine#27]
### Client Log

> [24Feb2024 19:01:27.489] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: POS_HUSK

**Comment by WindowsXPFake** [comment]
what mods are you using? only the end of herobrine?

**Comment by Krimatoria** [comment]
> what mods are you using? only the end of herobrine?

280+ mods maybe)

**Comment by WindowsXPFake** [comment]
seems like you didn't quite understand I meant like what are the name of the mods lol (sorry if this sounds rude) knowing the name would help identify the issue

**Comment by WindowsXPFake** [comment]
and the mod developer can fix it if they know what mods you're using

**Comment by Krimatoria** [comment]
> кажется, вы не совсем поняли, я имел в виду, как называются моды, лол (извините, если это звучит грубо), знание названия поможет определить проблему

Yes, I would like to know that) I just switched from 1.19.2 to 1.20.1 because the updated herobrine did not work for me. 

But I still have the build, I can try to run it tomorrow to try to figure out which mod does it. I saw in Discord that the updated version of Herobrine on 1.19.2 does not work for some. 

By the way, I switched to 1.20.1 and found an amazing bug, there's no other way to say it. I moved the entire build to 1.20.1 and couldn't figure out why mobs reset experience when killing each other, I just have a mod spore_1.20_1_2.0.3.jar [Fungal Infection:Spore] on 1.20.1 and there you can set mob targets that will attack the infected and that the infected would fight with other mobs and I saw that experience drops from them and this has never happened, because it only falls from killing a mob by a player. 

And I started looking for a mod that does this and it turned out to be Herobrine in 1.20.1 [endofherobrine-1.20.1-1.0.8.2.jar ] I removed it from the build and everything was fixed, the mobs no longer reset the experience. 

I described this whole big problem with an example of screenshots on the Discord server. I write through a translator, so the translation may not be accurate.

Lgow's Mods
![image](https://github.com/lgow/endofherobrine/assets/106809386/342529d9-9b35-4a3e-abb7-169196127b5c)
