### ISSUE TITLE
[Suggestion] Covert mode?

### ISSUE THREAD

**Issue by WaterOre** [lgow/endofherobrine#3]
Hi! I've been exploring your mod for a couple days, and so far I love the experience of sharing my world with Herobrine. I thought it might be fun to include this mod in a modpack and host it on a server without telling anyone that it's in there - would it be possible to add some kind of "covert mode" to the config? I'd like for players to be able to launch the menu, join a world, and play for a while without knowing that there's a creepypasta going on under their feet. This would ideally disable the custom splashes and advancement toast on initial spawn.

**Comment by lgow** [comment]
i can make a config to disable the advancements but not the splash texts
