### ISSUE TITLE
Can anyone help me with this error message?

### ISSUE THREAD

**Issue by MrScarfy** [lgow/endofherobrine#36]
Whenever I try to build the totem it always says; The current bossfights are merely placeholders. To summon them you have to enable experimental features. & I don't know how to enable it.
![image_2024-07-27_183734510](https://github.com/user-attachments/assets/97a7a05c-22fe-455a-af08-5837f8dff6bf)

**Comment by nhat2323** [comment]
Move to config folder in .minecraft ,find file endofherobrine-common.toml ,open it and change experimental = true 
![Screenshot 2024-08-06 111839](https://github.com/user-attachments/assets/86c4da61-44aa-4f33-87d9-463a7e158d35)
