### ISSUE TITLE
[1.18.2] Chicken Null Pointer Exception

### ISSUE THREAD

**Issue by LemonCeiling** [lgow/endofherobrine#5]
**Mod-Version:** Ex.: 1.18.2-1.0.5
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
...

**Expected behavior**
I am trying to play on a mc server that we made for this mod but I keep getting an error code

**Screenshots**
![Screenshot 2023-03-18 175534](https://user-images.githubusercontent.com/128263569/226144333-ae1e9ccd-d242-4546-9054-7dabc8845351.png)

**Additional context**

**Comment by lgow** [comment]
ok, I'll start backporting the latest update this week and I'll check it out

**Comment by LemonCeiling** [comment]
Thank you
