### ISSUE TITLE
Non-server owners don't see Herobrine.

### ISSUE THREAD

**Issue by Starblockset** [lgow/endofherobrine#6]
Awesome mod, really, but one issue is that when playing on a server, my friends see all the mobs and pigs and stuff, but not Herobrine himself. Even if they spawn him using a spawn egg or summon command. He just appears to be a pig every time.

**Comment by lgow** [comment]
are you using the mod in the intended modloader [forge]?

**Comment by Starblockset** [comment]
> are you using the mod in the intended modloader [forge]?

Yes I'm using forge.

**Comment by lgow** [comment]
Its hard for me to do anything about it if you don't provide the info requested at the issue template. No one has had this issue before I have no idea how to investigate that

**Comment by lgow** [comment]
please, open the issue again but giving the proper info requested in the template
