### ISSUE TITLE
[Suggestion] Add true boss battles

### ISSUE THREAD

**Issue by Steve982950** [lgow/endofherobrine#7]
**Is your feature request related to a problem? Please describe.**
Not related to a bug

(Ex. I'm always frustrated when [...])

**Describe the solution you'd like**
Can you add real boss battles? and make it so i defeat the boss, Herobrine leaves my world... forever

**Describe alternatives you've considered**
Make the boss (a bit) Harder rather than it just shooting Witherskulls

**Additional context**
That's all :)

**Comment by lgow** [comment]
It's planned, the project's still a work in progress

**Comment by lgow** [comment]
honestly, hard to set an exact date on it, I've explained the situation on the discord, consider joining us there to receive all the status updates!

**Comment by Steve982950** [comment]
ok lol
