### ISSUE TITLE
[1.19.3] Incompatibility with thehammermod

### ISSUE THREAD

**Issue by Shedao-Shai** [lgow/endofherobrine#8]
Forge: 44.1.17
End of Herobrine: 1.19.3-1.0.7
The Hammer Mod: 1.19.3-1.2

Crash occurs when breaking blocks with thehammermod tools, only occurs with The End of Herobrine installed. 

Link to crash log: https://gist.github.com/Shedao-Shai/b64452b42e7520920392b544dd18420e

**Comment by lgow** [comment]
patched! I'll post it later today, thanks for the first issue that actually gave me enough info to fix it quickly!

**Comment by Shedao-Shai** [comment]
Lmao you are welcome, for better or worse I report a lot of bugs on other mods ;)

**Comment by lgow** [comment]
definitely for better, lmao
