### ISSUE TITLE
[Suggestion] More Possessed Mobs

### ISSUE THREAD

**Issue by Steve982950** [lgow/endofherobrine#9]
**Is your feature request related to a problem? Please describe.**
No

(Ex. I'm always frustrated when [...])

**Describe the solution you'd like**
Hello Mr lgoww can u add more possessed mobs?

**Additional context**
Thats all :)

**Comment by lgow** [comment]
I will eventually, but I want every mob to have something special about them, not just being possessed for the sake of it
